function [fem, geoconst] = flowcell_nozzle_init(varargin)

% FEMLAB Model M-file
% Generated by FEMLAB 3.1 (FEMLAB 3.1.0.157, $Date: 2007-09-19 04:45:38 $)

flclear fem

% Femlab version
clear vrsn
vrsn.name = 'FEMLAB 3.1';
vrsn.ext = '';
vrsn.major = 0;
vrsn.build = 157;
vrsn.rcs = '$Name:  $';
vrsn.date = '$Date: 2007-09-19 04:45:38 $';
fem.version = vrsn;

% Constants
fem.const={'rho_sam','1e3','rho_buf','1e3','eta_sam','1e-3', ...
           'eta_buf','1e-3','D_sam','2.045e-9','v_sam', '6e-2', ...
           'v_buf','6e-2','concen_sam','1.0', 'concen_buf', '2.0', ...
           'D_buf','2.045e-9'};

mesh_factor = 10;
parse_varargin(varargin)

geoconst.width_inlet = 2.5e-5;
geoconst.width_side = 2.5e-5;
geoconst.width_outlet = 2.5e-5;
geoconst.length_inlet = 2e-4;;
geoconst.length_side = 3e-4;
geoconst.length_outlet = 6e-4;

% Geometry
carr={curve2([-3.0E-4,-3.0E-4],[2.5E-5,0],[1,1]), ...
  curve2([-3.0E-4,-7.5E-5],[0,0],[1,1]), ...
  curve2([-7.5E-5,-7.5E-5],[0,2.5E-5],[1,1]), ...
  curve2([-7.5E-5,-3.0E-4],[2.5E-5,2.5E-5],[1,1])};
g1=geomcoerce('solid',carr);
carr={curve2([-7.5E-5,-7.5E-5],[2.5E-5,0],[1,1]), ...
  curve2([-7.5E-5,1.5E-4],[0,0],[1,1]), ...
  curve2([1.5E-4,1.5E-4],[0,2.5E-5],[1,1]), ...
  curve2([1.5E-4,2.5E-5],[2.5E-5,2.5E-5],[1,1]), ...
  curve2([2.5E-5,2.5E-5],[2.5E-5,7.5E-5],[1,1]), ...
  curve2([2.5E-5,-2.5E-5],[7.5E-5,7.5E-5],[1,1]), ...
  curve2([-2.5E-5,-2.5E-5],[7.5E-5,2.5E-5],[1,1]), ...
  curve2([-2.5E-5,-7.5E-5],[2.5E-5,2.5E-5],[1,1])};
g2=geomcoerce('solid',carr);
carr={curve2([-2.5E-5,-2.5E-5],[2.5E-4,7.5E-5],[1,1]), ...
  curve2([-2.5E-5,2.5E-5],[7.5E-5,7.5E-5],[1,1]), ...
  curve2([2.5E-5,2.5E-5],[7.5E-5,2.5E-4],[1,1]), ...
  curve2([2.5E-5,-2.5E-5],[2.5E-4,2.5E-4],[1,1])};
g3=geomcoerce('solid',carr);
carr={curve2([1.5E-4,1.5E-4],[2.5E-5,0],[1,1]), ...
  curve2([1.5E-4,5.0E-4],[0,0],[1,1]), ...
  curve2([5.0E-4,5.0E-4],[0,2.5E-5],[1,1]), ...
  curve2([5.0E-4,1.5E-4],[2.5E-5,2.5E-5],[1,1])};
g4=geomcoerce('solid',carr);
carr={curve2([5.0E-4,5.0E-4],[2.5E-5,0],[1,1]), ...
  curve2([5.0E-4,0.0010],[0,0],[1,1]), ...
  curve2([0.0010,0.0010],[0,2.5E-5],[1,1]), ...
  curve2([0.0010,5.0E-4],[2.5E-5,2.5E-5],[1,1])};
g5=geomcoerce('solid',carr);


% Geometry 1 % newly added: the curved intersection

clear g2

carr={curve2([-7.5E-5,-2.5E-5,0],[2.5E-5,1.25E-5,1.25E-5],[1,0.707106781186548,1]), curve2([0,-2.5E-5,-2.5E-5],[1.25E-5,5.0E-5,7.5E-5],[1,0.707106781186548,1]),curve2([-2.5E-5,-7.5E-5],[7.5E-5,2.5E-5],[1,1])};
g11=geomcoerce('solid',carr);
clear g11
carr={curve2([-7.5E-5,-2.5E-5,0],[2.5E-5,1.25E-5,1.25E-5],[1, 0.707106781186548,1]), curve2([0,-2.5E-5,-2.5E-5],[1.25E-5,5.0E-5,7.5E-5],[1,0.707106781186548,1]),curve2([-2.5E-5,2.5E-5],[7.5E-5,7.5E-5],[1,1]), curve2([2.5E-5,2.5E-5],[7.5E-5,2.5E-5],[1,1]), curve2([2.5E-5,1.5E-4],[2.5E-5,2.5E-5],[1,1]), curve2([1.5E-4,1.5E-4],[2.5E-5,0],[1,1]), curve2([1.5E-4,-7.5E-5],[0,0],[1,1]), curve2([-7.5E-5,-7.5E-5],[0,2.5E-5],[1,1])};

g12=geomcoerce('solid',carr);

clear s
s.objs={g3,g4,g1,g5,g12};
s.name={'CO3','CO4','CO1','CO5','CO2'};
s.tags={'g3','g4','g1','g5','g12'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);

% Initialize mesh for geometry 1
init_size = 2.5e-5/mesh_factor;
fem.mesh=meshinit(fem, 'hmax',[init_size*6], 'hmaxfact',1, 'hgrad',1.3, ...
                  'hcurve',0.3, 'hcutoff',0.001, 'hnarrow',1, ...
                  'hpnt',10, 'xscale',1.0, 'yscale',1.0, 'mlevel','sub', ...
                  'hgradedg', [5,1.2,13,1.2,16,1.2], 'hmaxedg',[5, ...
                    init_size/10,13,init_size/6,16,init_size/4, 19, ...
                    init_size/8, 20, init_size/8], 'hmaxsub',[2, ...
                    init_size,4,init_size*3]);

% fem.mesh=meshinit(fem, 'hmax',[init_size*6],  'hgradedg',[5,1.2,15, ...
%                     1.2,18,1.2], 'hmaxedg',[5,init_size/10, 6, ...
%                     init_size/10, 7, init_size/10, 15, init_size/6,18, ...
%                     init_size/4], 'hmaxsub',[2, init_size, 4, ...
%                     init_size*3]);
% 


% Extend mesh
fem.xmesh=meshextend(fem);

%********************
%
% Physics settings
%
%********************

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.mode.type = 'cartesian';
appl.dim = {'u','v','p'};
appl.sdim = {'x','y','z'};
appl.name = 'ns';
appl.shape = {'shlag(2,''u'')','shlag(2,''v'')','shlag(1,''p'')'};
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.sshape = 2;
appl.border = 'off';
appl.assignsuffix = '_ns';
clear prop
prop.elemdefault='Lagp2p1';
prop.stensor='full';
prop.weakconstr=struct('value',{'off'},'dim',{{'lm1','lm2'}});
appl.prop = prop;
clear pnt
pnt.p0 = 0;
pnt.pnton = 0;
pnt.ind = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.type = {'noslip','neutral','uv','slip','uv','out','noslip'};
bnd.u0 = {0,0,'v_sam*3/2*(1-s*s)',0,0,0,0};
bnd.v0 = {0,0,0,0,'-v_buf*6*s*(1-s)',0,'-v_buf*6*s*(1-s)'};
bnd.p0 = 0;
bnd.ind = [3,4,1,2,4,1,2,5,1,7,1,2,4,1,2,4,1,6,1,1];
appl.bnd = bnd;
clear equ
equ.shape = [1;2;3];
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.init = {{'v_sam';0;0},{'v_sam/2';'-v_buf/2';0},{0;'-v_buf';0},{'v_sam+v_buf*2';0;0}};
equ.usage = 1;
equ.rho = {'rho_sam','rho_sam','rho_buf','rho_sam'};
equ.eta = {'eta_sam','eta_sam','eta_buf','eta_sam'};
equ.F_x = 0;
equ.F_y = 0;
equ.idon = 0;
equ.delid = 0.5;
equ.sdon = 0;
equ.sdtype = 'pgc';
equ.delsd = 0.25;
equ.cdon = 0;
equ.cdtype = 'sc';
equ.delcd = 0.35;
equ.pson = 0;
equ.delps = 1;
equ.ind = [1,2,3,4,4];
appl.equ = equ;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'FlConvDiff';
appl.mode.type = 'cartesian';
appl.dim = {'c'};
appl.sdim = {'x','y','z'};
appl.name = 'cd';
appl.shape = {'shlag(2,''c'')'};
appl.gporder = 4;
appl.cporder = 2;
appl.sshape = 2;
appl.border = 'off';
appl.assignsuffix = '_cd';
clear prop
prop.elemdefault='Lag2';
prop.equform='noncons';
prop.weakconstr=struct('value',{'off'},'dim',{{'lm3'}});
appl.prop = prop;
clear bnd
bnd.N = 0;
bnd.c0 = {'concen_sam',0,0,'concen_buf',0,'concen_buf'};
bnd.type = {'C','N0','cont','C','Nc','N0'};
bnd.ind = [1,2,2,3,2,2,3,4,2,6,2,3,2,2,3,2,2,5,2,2];
appl.bnd = bnd;
clear equ
equ.shape = 1;
equ.gporder = 1;
equ.cporder = 1;
equ.init = {'concen_sam','concen_buf*2/3','concen_buf'};
equ.usage = 1;
equ.D = 'D_buf';
equ.dtensor = 1;
equ.dtype = 'iso';
equ.R = 0;
equ.Dts = 1;
equ.u = 'u';
equ.v = 'v';
equ.idon = 0;
equ.delid = 0.5;
equ.sdon = 0;
equ.sdtype = 'pgc';
equ.delsd = 0.25;
equ.cdon = 0;
equ.cdtype = 'sc';
equ.delcd = 0.35;
equ.ind = [1,2,3,2,2];
appl.equ = equ;
fem.appl{2} = appl;
fem.sdim = {'x','y'};

% Simplify expressions
fem.simplify = 'on';
fem.border = 1;

% Global expressions
fem.expr = {};

% Multiphysics
fem=multiphysics(fem);
