function sIqgetx = iqgetx_init(varargin)
% --- Usage:
%        sIqgetx = iqgetx_init(varargin)
% --- Purpose:
%        Initialize the IqGetX structure.
%
% --- Parameter(s):
%        varargin - 'onebuf' (default) or 'twobuf' (before and after)
%
% $Id: iqgetx_init.m,v 1.7 2014/04/05 19:37:47 xqiu Exp $
%

onebuf = 1;
twobuf = 0;
parse_varargin(varargin);


% darksub: set to 1 when buf and sam share the common dark images
%          to avoid redundant loading of the dark images. 
if (onebuf == 1) && (twobuf == 0)
   sIqgetx = struct('x', [], ...
                    'label', '', ...
                    'title', '', ...
                    'expt_type', 'SAXS', ...  % 'SAXS', 'ASAXS', 'TRSAXS'
                    'dataformat', 'SG1KCCD', ...
                    'datadir', '', ...
                    'time', '', ...
                    'expotime', 0, ...
                    'samprefix', '', ...
                    'bufprefix', '', ...
                    'suffix', '.tif', ...
                    'specfile', '', ...
                    'specdata', [], ...
                    'runnums_autogen', 0, ...
                    'run_config', [2,2,4,2], ... % [dark, buf1, sam, buf2]/[dark, buf, sam]
                    'startnum', [], ...
                    'darknums', [], ...
                    'bufnums', [], ... % onebuf only
                    'samnums', [], ...
                    'skipnums', [], ...
                    'num_digits', 1, ...
                    'readraw', 1, ...
                    'invertim', 0, ...
                    'darksub', 1, ...
                    'dezinger', 1, ...
                    'correct', 1, ...
                    'lblcorrect', 0, ...
                    'setbkgzero', 0, ...
                    'normalize', 1, ...
                    'keep_im', 0, ...
                    'im_dark', 0, ...
                    'normconst_dark',0, ...
                    'moncounts_dark', 0, ...
                    'samimgs', [], ...
                    'sam', [], ...
                    'bufimgs', [], ...
                    'buf', [], ...
                    'iq', []);

end

if (twobuf == 1)
   sIqgetx = struct('x', [], ...
                    'label', '', ...
                    'title', '', ...
                    'expt_type', 'SAXS', ...  % 'SAXS', 'ASAXS', 'TRSAXS'
                    'dataformat', 'SG1KCCD', ...
                    'datadir', '', ...
                    'time', '', ...
                    'expotime', 0, ...
                    'samprefix', '', ...
                    'bufprefix', '', ...
                    'suffix', '.tif', ...
                    'specfile', '', ...
                    'specdata', [], ...
                    'runnums_autogen', 0, ...
                    'run_config', [2,2,4,2], ... % [dark, buf1, sam, buf2]/[dark, buf, sam]
                    'startnum', [], ...
                    'darknums', [], ...
                    'buf1nums', [], ... % twobuf only
                    'samnums', [], ...
                    'buf2nums', [], ... % twobuf only
                    'skipnums', [], ...
                    'num_digits', 1, ...
                    'readraw', 1, ...
                    'invertim', 0, ...
                    'darksub', 1, ...
                    'dezinger', 1, ...
                    'correct', 1, ...
                    'lblcorrect', 0, ...
                    'setbkgzero', 0, ...
                    'normalize', 1, ...
                    'keep_im', 0, ...
                    'im_dark', 0, ...
                    'normconst_dark',0, ...
                    'moncounts_dark', 0, ...
                    'samimgs', [], ...
                    'sam', [], ...
                    'buf1imgs', [], ... % twobuf only
                    'buf1', [], ...     % twobuf only
                    'buf2imgs', [], ... % twobuf only
                    'buf2', [], ...     % twobuf only
                    'bufimgs', [], ...
                    'buf', [], ...
                    'iq', []);

end
