function [peak, fitresult, gof] = myFit(data,xmin,xmax,type)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jul-2014 11:45:58

%% Fit: 'untitled fit 1'.
index = (data(:,1) >= xmin) & (data(:,1) <= xmax);
xData = data(index,1);
yData = data(index,2);
% [xData, yData] = prepareCurveData( x, y );

switch lower(type)
    case 'gauss'
        % Set up fittype and options.
        ft = fittype( 'gauss1' );
        opts = fitoptions( ft );
        opts.Display = 'Off';
        opts.Lower = [-Inf -Inf 0];
        opts.StartPoint = [7.09808949753307e-09 0.036872 0.0117061035083296];
        opts.Upper = [Inf Inf Inf];
    case 'polynomial'
        % Set up fittype and options.
        ft = fittype( 'poly8' );
        opts = fitoptions( ft );
        opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf];
        opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf];
end

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on
y_fit = feval(fitresult, xData);
[~,peak_index] = max(y_fit);
peak = xData(peak_index);
title(['peak at x=',num2str(peak)]);
fprintf('peak at x=%2.4f\n',peak);
vline(xData(peak_index),'linestyle', '--', 'color', [0.2 0.2 0.2]);
