function z=protno(element)
%PROTNO    returns proton number of specified element

%1997 by Pavol
ELS = [...
'H ',                             'He',...
'LiBe'                  'B C N O F Ne',...
'NaMg',                 'AlSiP S ClAr',...
'K CaScTiV CrMnFeCoNiCuZnGaGeAsSeBrKr',...
'RbSrY ZrNbMoTcRuRhPdAgCdInSnSbTeI Xe',...
'CsBaLa',...
    'CePrNdPmSmEuGdTbDyHoErTmYbLu',...
      'HfTaW ReOsIrPtAuHgTlPbBiPoAtRn',...
'FrRaAc'...
    'ThPaU '...
];
if length(element)==1
	element=[element ' '];
end
z=(findstr(element,ELS)+1)/2;
