function TEMPLATE()
%TEMPLATE  figure template for AGBPLOT
% recommended global cellno = [12 36]

% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
%


a = figure;
set(a,'PaperUnits','centimeters', ...
	'PaperPosition',[0.89 2.69 18 26.2], ...
	'PaperType','a4letter', ...
	'Position',[212 45 581 512]);
set(a,'Interruptible','yes');
b = axes('Parent',a);
set(b,'DrawMode','fast', ...
	'NextPlot','add', ...
	'Position',[0.53 0 0.47 0.97], ...
	'Xform',eye(4), ...
	'XLim',[-23.9375 23.9375], ...
	'XLimMode','manual', ...
	'XTick',[], ...
	'XTickMode','manual', ...
	'YLim',[-70.9925 70.9925], ...
	'YLimMode','manual', ...
	'YTick',[], ...
	'YTickMode','manual');
set(b,'Tag','AGB', ...
	'Visible','off');
c = text('Parent',b);
set(c,'Units','pixels', ...
	'EraseMode','normal', ...
	'HorizontalAlignment','center', ...
	'Position',[136 505], ...
	'String','Asym. [4 10; 6 9], th=[21.50 33.28]', ...
	'VerticalAlignment','bottom');
set(b,'Title',c);
b = axes('Parent',a);
set(b,'Box','on', ...
	'Color',[0 0 0], ...
	'DrawMode','fast', ...
	'NextPlot','add', ...
	'Position',[0.92 0 0.08 0.12], ...
	'Xform',eye(4), ...
	'XLimMode','manual', ...
	'XTick',-1, ...
	'XTickLabels','', ...
	'XTickLabelMode','manual', ...
	'XTickMode','manual', ...
	'YLimMode','manual', ...
	'YTick',-1, ...
	'YTickLabels','', ...
	'YTickLabelMode','manual', ...
	'YTickMode','manual');
set(b,'Tag','legend', ...
	'UserData',[1.1 124.00146484375 0.53 0 0.47 0.97 1]);
c = text('Parent',b);
set(c,'EraseMode','normal', ...
	'Position',[0.47644 0.8 0], ...
	'String','Y ');
c = line('Parent',b);
set(c,'Color',[0 1 0], ...
	'LineStyle','o', ...
	'MarkerSize',4, ...
	'Xdata',0.170157, ...
	'Ydata',0.8);
c = text('Parent',b);
set(c,'EraseMode','normal', ...
	'Position',[0.47644 0.6 0], ...
	'String','Cu');
c = line('Parent',b);
set(c,'Color',[1 0 0], ...
	'LineStyle','.', ...
	'MarkerSize',13, ...
	'Xdata',0.170157, ...
	'Ydata',0.6);
c = text('Parent',b);
set(c,'EraseMode','normal', ...
	'Position',[0.47644 0.4 0], ...
	'String','O1');
c = line('Parent',b);
set(c,'Color',[0 1 1], ...
	'LineStyle','x', ...
	'MarkerSize',4, ...
	'Xdata',0.170157, ...
	'Ydata',0.4);
c = text('Parent',b);
set(c,'EraseMode','normal', ...
	'Position',[0.47644 0.2 0], ...
	'String','O2');
c = line('Parent',b);
set(c,'Color',[0 1 1], ...
	'LineStyle','+', ...
	'MarkerSize',4, ...
	'Xdata',0.170157, ...
	'Ydata',0.2);
b = axes('Parent',a);
set(b,'DrawMode','fast', ...
	'NextPlot','add', ...
	'Position',[0 0 0.47 0.97], ...
	'Xform',eye(4), ...
	'XLim',[-23.9375 23.9375], ...
	'XLimMode','manual', ...
	'XTick',[], ...
	'XTickMode','manual', ...
	'YLim',[-70.9925 70.9925], ...
	'YLimMode','manual', ...
	'YTick',[], ...
	'YTickMode','manual');
set(b,'Interruptible','yes', ...
	'Tag','AGB', ...
	'Visible','off');
c = text('Parent',b);
set(c,'Units','pixels', ...
	'EraseMode','normal', ...
	'HorizontalAlignment','center', ...
	'Position',[136 505], ...
	'String','Asym. [0 5; 3 4], th=[0 36.44]', ...
	'VerticalAlignment','bottom');
set(b,'Title',c);
