% FEMLAB Model M-file
% Generated by FEMLAB 3.1 (FEMLAB 3.1.0.157, $Date: 2007-09-19 04:45:38 $)

flclear fem

% Femlab version
clear vrsn
vrsn.name = 'FEMLAB 3.1';
vrsn.ext = '';
vrsn.major = 0;
vrsn.build = 157;
vrsn.rcs = '$Name:  $';
vrsn.date = '$Date: 2007-09-19 04:45:38 $';
fem.version = vrsn;

% Geometry
carr={curve2([-3.0E-4,-3.0E-4],[2.5E-5,0],[1,1]), ...
  curve2([-3.0E-4,-1.0E-4],[0,0],[1,1]), ...
  curve2([-1.0E-4,-1.0E-4],[0,2.5E-5],[1,1]), ...
  curve2([-1.0E-4,-3.0E-4],[2.5E-5,2.5E-5],[1,1])};
g1=geomcoerce('solid',carr);
carr={curve2([-1.0E-4,-1.0E-4],[2.5E-5,0],[1,1]), ...
  curve2([-1.0E-4,1.75E-4],[0,0],[1,1]), ...
  curve2([1.75E-4,1.75E-4],[0,2.5E-5],[1,1]), ...
  curve2([1.75E-4,5.0E-5],[2.5E-5,2.5E-5],[1,1]), ...
  curve2([5.0E-5,2.5E-5,2.5E-5],[2.5E-5,2.5E-5,5.0E-5],[1,0.707106781186548,1]), ...
  curve2([2.5E-5,2.5E-5],[5.0E-5,1.0E-4],[1,1]), ...
  curve2([2.5E-5,-2.5E-5],[1.0E-4,1.0E-4],[1,1]), ...
  curve2([-2.5E-5,-2.5E-5],[1.0E-4,5.0E-5],[1,1]), ...
  curve2([-2.5E-5,-2.5E-5,-5.0E-5],[5.0E-5,2.5E-5,2.5E-5],[1,0.707106781186548,1]), ...
  curve2([-5.0E-5,-1.0E-4],[2.5E-5,2.5E-5],[1,1])};
g2=geomcoerce('solid',carr);
carr={curve2([-2.5E-5,-2.5E-5],[2.25E-4,1.0E-4],[1,1]), ...
  curve2([-2.5E-5,2.5E-5],[1.0E-4,1.0E-4],[1,1]), ...
  curve2([2.5E-5,2.5E-5],[1.0E-4,2.25E-4],[1,1]), ...
  curve2([2.5E-5,-2.5E-5],[2.25E-4,2.25E-4],[1,1])};
g3=geomcoerce('solid',carr);
carr={curve2([1.75E-4,1.75E-4],[2.5E-5,0],[1,1]), ...
  curve2([1.75E-4,5.0E-4],[0,0],[1,1]), ...
  curve2([5.0E-4,5.0E-4],[0,2.5E-5],[1,1]), ...
  curve2([5.0E-4,1.75E-4],[2.5E-5,2.5E-5],[1,1])};
g4=geomcoerce('solid',carr);
carr={curve2([5.0E-4,5.0E-4],[2.5E-5,0],[1,1]), ...
  curve2([5.0E-4,0.0010],[0,0],[1,1]), ...
  curve2([0.0010,0.0010],[0,2.5E-5],[1,1]), ...
  curve2([0.0010,5.0E-4],[2.5E-5,2.5E-5],[1,1])};
g5=geomcoerce('solid',carr);
clear s
s.objs={g1,g2,g3,g4,g5};
s.name={'CO1','CO2','CO3','CO4','CO5'};
s.tags={'g1','g2','g3','g4','g5'};

fem.draw=struct('s',s);

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.mode.type = 'cartesian';
appl.dim = {'u','v','p'};
appl.sdim = {'x','y','z'};
appl.name = 'ns';
appl.shape = {};
appl.gporder = {};
appl.cporder = {};
appl.sshape = 2;
appl.border = 'off';
appl.assignsuffix = '_ns';
clear prop
prop.elemdefault='Lagp2p1';
prop.stensor='full';
prop.weakconstr=struct('value',{'off'},'dim',{{'lm1','lm2'}});
appl.prop = prop;
clear pnt
pnt.p0 = {};
pnt.pnton = {};
pnt.ind = [];
appl.pnt = pnt;
clear bnd
bnd.type = {};
bnd.u0 = {};
bnd.v0 = {};
bnd.p0 = {};
bnd.ind = [];
appl.bnd = bnd;
clear equ
equ.shape = {};
equ.gporder = {};
equ.cporder = {};
equ.init = {};
equ.usage = {};
equ.rho = {};
equ.eta = {};
equ.F_x = {};
equ.F_y = {};
equ.idon = {};
equ.delid = {};
equ.sdon = {};
equ.sdtype = {};
equ.delsd = {};
equ.cdon = {};
equ.cdtype = {};
equ.delcd = {};
equ.pson = {};
equ.delps = {};
equ.ind = [];
appl.equ = equ;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'FlConvDiff';
appl.mode.type = 'cartesian';
appl.dim = {'c'};
appl.sdim = {'x','y','z'};
appl.name = 'cd';
appl.shape = {};
appl.gporder = {};
appl.cporder = {};
appl.sshape = 2;
appl.border = 'off';
appl.assignsuffix = '_cd';
clear prop
prop.elemdefault='Lag2';
prop.equform='noncons';
prop.weakconstr=struct('value',{'off'},'dim',{{'lm3'}});
appl.prop = prop;
clear bnd
bnd.N = {};
bnd.c0 = {};
bnd.type = {};
bnd.ind = [];
appl.bnd = bnd;
clear equ
equ.shape = {};
equ.gporder = {};
equ.cporder = {};
equ.init = {};
equ.usage = {};
equ.D = {};
equ.dtensor = {};
equ.dtype = {};
equ.R = {};
equ.Dts = {};
equ.u = {};
equ.v = {};
equ.idon = {};
equ.delid = {};
equ.sdon = {};
equ.sdtype = {};
equ.delsd = {};
equ.cdon = {};
equ.cdtype = {};
equ.delcd = {};
equ.ind = [];
appl.equ = equ;
fem.appl{2} = appl;
fem.sdim = {'x','y'};

% Simplify expressions
fem.simplify = 'on';
fem.border = 1;

% Global expressions
fem.expr = {};

% Functions
clear fcns
fem.functions = {};

% Multiphysics
fem=multiphysics(fem);
