function texstr = atomdb_textable(varargin)
% --- Usage:
%        texstr = atomdb_textable(varargin)
% --- Purpose:
%        output the atomdb content to TEX table format cell array
%        for printing with LaTEX
% --- Parameter(s):
%     
% --- Return(s): 
%        texstr - a cell array of the content
%
% --- Example(s):
%
% $Id: atomdb_textable.m,v 1.3 2013/02/28 16:52:09 schowell Exp $
%

global atomdb_isvalid atomdb_num atomdb_sym atomdb_const atomdb_sas ...
    atomdb_nucleic atomdb_protein atomdb_sugar atomdb_asfcoeftb ...
    atomdb_compcoeftb atomdb_macoeftb atomdb_bindenergytb ...
    atomdb_xxsectiontb atomdb_f1f2coeftb

% small angle scattering data
sasdata = [atomdb_sas.z', atomdb_sas.charge', atomdb_sas.radius_sol', ...
           atomdb_sas.exclvolume', atomdb_sas.z_sol'];

labels_col = {'Z', 'charge', 'hydrated radius (A)', ['excluded ' ...
                    'volume (A3)'] 'eff. Z'};
caption = ['Atomic (group) types supported for solution small angle ' ...
           'scattering calculations'];

arr2textable(sasdata, 'align', {'|r|r|r|r|r|r|'}, 'labels_row', ...
             atomdb_sas.name, 'labels_col', labels_col, 'caption', ...
             {caption}, 'data_format', {'%2d', '%2d', '%5.2f', ...
                    '%8.4f', '%0.2f'});

% nucleic acid data
caption = ['Nucleic acids atomic (group) types corresponding to the ' ...
           'data base entries above.'];
arr2textable(atomdb_nucleic.sastype,  'labels_row', atomdb_nucleic.name, ...
             'labels_col', atomdb_nucleic.resname, 'caption', {caption});

% atomic constants data
caption = 'Atomic constant table of some physical properties.';
arr2textable(atomdb_const.data,  'labels_row', atomdb_const.row_names, ...
             'labels_col', atomdb_const.column_names, 'caption', ...
             {caption}, 'data_format', {'%3i', '%5.2f', '%5.2f', ...
                    '%12.7f', '%10.4f', '%10.4f', '%10.4f', '%6.3f', ...
                    '%9.5f', '%8.4f', '%10.4f'});
