function data = GetQk(k,a,b,z1,z2,c1,c2,d1,d2)
%data = GetQk(k,a,b,z1,z2,c1,c2,d1,d2)

E=exp(1);
ImaginaryI = sqrt(-1);

data=    (b.*((E.^((ImaginaryI).*k)./k.^2 - (1 + (ImaginaryI) ... 
.*k)./k.^2)) +  ... 
      1./2.*a.*(((E.^((ImaginaryI).*k).*((2.* ... 
(ImaginaryI) + 2.*k)))./k.^3 - (2.*(ImaginaryI) + (ImaginaryI).* ... 
k.^2)./k.^3)) +  ... 
      c1.*(((-((E.^(-z1).*(((-k) + E.^z1 ... 
.*k - (ImaginaryI).*z1)))./(k.*(((ImaginaryI).*k -  ... 
                        z1))))) - ((ImaginaryI).*E.^( ... 
(ImaginaryI).*((k + (ImaginaryI).*z1))).*z1)./(k.*(((ImaginaryI).*k  ... 
- z1))))) + ((ImaginaryI).*((d2.*((k + (ImaginaryI).*z1)) + d1.*((k  ... 
+ (ImaginaryI).*z2)))))./(((k + (ImaginaryI).*z1)).*((k +  ... 
(ImaginaryI).*z2))) +  ... 
      c2.*(((-((E.^(-z2).*(((-k) + E.^z2 ... 
.*k - (ImaginaryI).*z2)))./(k.*(((ImaginaryI).*k -  ... 
                        z2))))) - ((ImaginaryI).*E.^( ... 
(ImaginaryI).*((k + (ImaginaryI).*z2))).*z2)./(k.*(((ImaginaryI).*k  ... 
- z2)))))) ;