function pdata
%PDATA     set path to DATA

pj=pjtbxdir('pavol');
dat=pjtbxdir('data');

addpath([pj '/data'],...
	[pj '/work'],...
	[dat '/bnl'],...
	[dat '/pswti'],...
	[dat '/pswtn'],...
	[dat '/psw'],...
	'-end');
%cd(dat);
